
version: '3.8'
services:
  mysqldb:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=rami
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8082:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/timeSheetDevOps?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "rami"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysqldb

